package com.example.demo.entities;
// Generated 04-jul-2019 21:58:16 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Carga generated by hbm2java
 */
@Entity
@Table(name = "carga", catalog = "cargabd")
public class Carga implements java.io.Serializable {

	private int idcarga;
	private Docente docente;
	private short horas;
	private long idsemestre;

	public Carga() {
	}

	public Carga(int idcarga, Docente docente, short horas, long idsemestre) {
		this.idcarga = idcarga;
		this.docente = docente;
		this.horas = horas;
		this.idsemestre = idsemestre;
	}

	@Id

	@Column(name = "idcarga", unique = true, nullable = false)
	public int getIdcarga() {
		return this.idcarga;
	}

	public void setIdcarga(int idcarga) {
		this.idcarga = idcarga;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddocente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "horas", nullable = false)
	public short getHoras() {
		return this.horas;
	}

	public void setHoras(short horas) {
		this.horas = horas;
	}

	@Column(name = "idsemestre", nullable = false)
	public long getIdsemestre() {
		return this.idsemestre;
	}

	public void setIdsemestre(long idsemestre) {
		this.idsemestre = idsemestre;
	}

}
