package com.example.demo.entities;
// Generated 16-jul-2019 17:55:55 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso", catalog = "cargabd")
public class Curso implements java.io.Serializable {

	private Integer idcurso;
	private String nombre;
	private byte horassemanales;
	private String tipo;
	private Set<Docente> docentes = new HashSet<Docente>(0);

	public Curso() {
	}

	public Curso(String nombre, byte horassemanales, String tipo) {
		this.nombre = nombre;
		this.horassemanales = horassemanales;
		this.tipo = tipo;
	}

	public Curso(String nombre, byte horassemanales, String tipo, Set<Docente> docentes) {
		this.nombre = nombre;
		this.horassemanales = horassemanales;
		this.tipo = tipo;
		this.docentes = docentes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcurso", unique = true, nullable = false)
	public Integer getIdcurso() {
		return this.idcurso;
	}

	public void setIdcurso(Integer idcurso) {
		this.idcurso = idcurso;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "horassemanales", nullable = false)
	public byte getHorassemanales() {
		return this.horassemanales;
	}

	public void setHorassemanales(byte horassemanales) {
		this.horassemanales = horassemanales;
	}

	@Column(name = "tipo", nullable = false, length = 10)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
	public Set<Docente> getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set<Docente> docentes) {
		this.docentes = docentes;
	}

}
