package com.example.demo.entities;
// Generated 04-jul-2019 21:58:16 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "cargabd")
public class Docente implements java.io.Serializable {

	private Integer idDocente;
	private Curso curso;
	private String nombres;
	private String apellidos;
	private Set<Carga> cargas = new HashSet<Carga>(0);

	public Docente() {
	}

	public Docente(Curso curso, String nombres, String apellidos) {
		this.curso = curso;
		this.nombres = nombres;
		this.apellidos = apellidos;
	}

	public Docente(Curso curso, String nombres, String apellidos, Set<Carga> cargas) {
		this.curso = curso;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.cargas = cargas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDocente", unique = true, nullable = false)
	public Integer getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(Integer idDocente) {
		this.idDocente = idDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCurso", nullable = false)
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@Column(name = "Nombres", nullable = false, length = 40)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "Apellidos", nullable = false, length = 40)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<Carga> getCargas() {
		return this.cargas;
	}

	public void setCargas(Set<Carga> cargas) {
		this.cargas = cargas;
	}

}
