package com.example.demo.entities;
// Generated 11-jul-2019 22:05:43 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semestreacademico generated by hbm2java
 */
@Entity
@Table(name = "semestreacademico", catalog = "cargabd")
public class Semestreacademico implements java.io.Serializable {

	private int ciclo;
	private Set<Carga> cargas = new HashSet<Carga>(0);

	public Semestreacademico() {
	}

	public Semestreacademico(int ciclo) {
		this.ciclo = ciclo;
	}

	public Semestreacademico(int ciclo, Set<Carga> cargas) {
		this.ciclo = ciclo;
		this.cargas = cargas;
	}

	@Id

	@Column(name = "ciclo", unique = true, nullable = false)
	public int getCiclo() {
		return this.ciclo;
	}

	public void setCiclo(int ciclo) {
		this.ciclo = ciclo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semestreacademico")
	public Set<Carga> getCargas() {
		return this.cargas;
	}

	public void setCargas(Set<Carga> cargas) {
		this.cargas = cargas;
	}

}
