package com.example.demo.entities;
// Generated 04-jul-2019 21:58:16 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Semestreacademico generated by hbm2java
 */
@Entity
@Table(name = "semestreacademico", catalog = "cargabd")
public class Semestreacademico implements java.io.Serializable {

	private Integer idSemestre;
	private int ciclo;

	public Semestreacademico() {
	}

	public Semestreacademico(int ciclo) {
		this.ciclo = ciclo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSemestre", unique = true, nullable = false)
	public Integer getIdSemestre() {
		return this.idSemestre;
	}

	public void setIdSemestre(Integer idSemestre) {
		this.idSemestre = idSemestre;
	}

	@Column(name = "ciclo", nullable = false)
	public int getCiclo() {
		return this.ciclo;
	}

	public void setCiclo(int ciclo) {
		this.ciclo = ciclo;
	}

}
